# FROM jupyter/base-notebook
FROM jupyter/tensorflow-notebook
MAINTAINER threeq<threeq@foxmail.com>

# see https://hub.docker.com/u/jupyter/
# see https://github.com/jupyter/docker-stacks/blob/master/docs/using/selecting.md

RUN pip install --upgrade pip
